name: brick_craft
description: A new Flutter project.


publish_to: 'none'

version: 0.1.1+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  webviewx: ^0.2.1
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0



flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: nanum
      fonts:
        - asset: assets/nanumB.ttf
          weight: 900
        - asset: assets/nanumB.ttf
          weight: 700
        - asset: assets/nanumB.ttf
        - asset: assets/nanumL.ttf
          weight: 100